### ISSUE TITLE
Querying a graph database instead of using GHC-API?

### ISSUE THREAD

**Issue by tkvogt** [haskell/haskell-ide-engine#10]
There are some problems with the GHC-API as mentioned here:
https://github.com/fpco/haskell-ide/wiki/GHC-API

I think that several of these problems could be solved by storing code, type Information, cabal data in a graph database. The idea would be to query this database instead of using GHC-API. GHC-API is just used to fill the db: [Neo4j](http://neo4j.com/).
The reason for me to come up with a graph database in the first place was to answer the following questions:
- Which functions are most often applied to a certain type?
- How do I get from a type A to a type B? E.g. I get from String to Text by Data.Text.pack

In order to achieve this we have to store all repos from github/hackage/stackage in this database.
The are a lot of advantages:
- A graph instead of a constructor tree in GHC-API allows to find reverse dependencies (not on packages but on functions: Does anybody use this library function or can I deprecate it? With what parameters do others use this function?)
- A query language like Cypher is more powerful than a traversal of a ghc tree of constructors.
- A more general access to data sources like code, cabal-files, github

The only disadvantage is that this database would have to be maintained and therefore more likely would be a service instead of being installed locally.
I plan to implement this and have looked into ghc-exactprint and hoogle and made some experiments with GHC-API. Anything else I should look into? Would you like to have this?

**Comment by mgsloan** [comment]
This is a really cool idea!  @epost mentioned something similar [here](https://github.com/haskell/haskell-ide/issues/2#issuecomment-150833146), linking to [this gist](https://gist.github.com/epost/de87e67558a18de6716a).

I've been thinking similarly that it would be great to collect and cache this info.  This way, you could jump into the code of your dependencies, and query info without compiling it, and in general perform interesting cross-project analysis.  This could also be used to power even better haddock source listings - type info as well as the identifier links.  Identifier links could jump into haddock source listings from other projects (doesn't seem to work this way yet).

So yes, I personally would like to have this.  So, If not at the core of haskell-ide, this certainly falls under the umbrella of things which can be implemented atop it.

There's some ide-backend code which might be interesting to reference.  While ide-backend does not have an actual database, it does have a single datatype for all collected info, which is potentially serializable: https://github.com/fpco/ide-backend/blob/3419618c714d0775d1eb17334d1277e166c5a78a/ide-backend/IdeSession/State.hs#L65

Treating collected info as a database makes a whole bunch of sense.  This could provide a nice mid-level API for writing the IDE protocol queries.  So, I'm thinking that even if it's possible to query the database via the protocol, the main IDE protocol should wrap up common editor functionality in a more straightforward interface.

The primary use-case of haskell-ide is providing information about code that you're working on.  I'm a little concerned that using a proper database for the info resulting from this would be overkill.  It would take a lot more time to store this info, and probably not that many queries would be executed.  In other words, this is a tradeoff between compile times (including storing info) and query latency.

Way back in the day, I influenced the implementation to use an `IntervalMap` for sub expression type info since it matched the types of queries I wanted to do.  Now, I'm thinking this was a mistake, as it takes longer to build the datastructure, just for the benefit of 

So, I guess the ideal thing would be to be able to run these queries against either a very simplistic database (which is populated very quickly) or a proper database.  This proper database would be queried when we have cached compilation info, or for more involved, complicated queries.

> The only disadvantage is that this database would have to be maintained and therefore more likely would be a service instead of being installed locally.

I see no reason why such a database couldn't be populated locally, possibly even being generated when info for a package is demanded.  As such, having it as a service or global cache is just an optimization, and one that could cause inconsistencies, such as if the user has a different build environment.

**Comment by alanz** [comment]
It may be worth looking at https://github.com/nominolo/scion-tools and its predecessor https://github.com/nominolo/scion, as well as what the leksah server is doing in terms of managing all the information around a project.

**Comment by tkvogt** [comment]
Thanks for the feedback so far.
> I see no reason why such a database couldn't be populated locally, possibly even being generated when info for a package is demanded. As such, having it as a service or global cache is just an optimization, and one that could cause inconsistencies, such as if the user has a different build environment.

It has to be a service! There is just to much data, that has to be constantly updated. Let me give an example:
- For what I want to achieve I need to store the 40.000 repos from github in neo4j. If everyone of these uses "map" 10 times then there are 400.000 edges between the "map"-node and its first argument in all these repos. Furthermore a type hierarchy has to be built in to classify the 400.000 edges. It also has to be updated regularly. Then there different library versions, that compile with different ghc versions.

Because of this I would also not try to replace fast and working code. What if the server goes down?
I see it more like an extra service where it is OK to wait 200 ms for an answer. But maybe one could generate smaller tables from this massive db, like condensed knowledge.
The problem of what function to use next is in my opinion so important that solving this well could mean a breakthrough for the Haskell community. I am 100% committed to try this.

**Comment by JPMoresmau** [comment]
I had started toying with this idea at https://github.com/JPMoresmau/dbIDE/tree/master/as-browser. The idea was to use acid-state to have a database of hackage and local projects, with their modules and symbols, to be easily searchable. Getting the packages from Hackage was not that slow, a few minutes if I remember.

**Comment by tkvogt** [comment]
Interesting! We may have very similar goals.
Since I know graph databases, I see relational databases as inferior. Some things I don't know:
- Can acid-state be used like a graph db?
- Is [graph-db](https://github.com/nikita-volkov/graph-db) usable? I currently prefer neo4j because it is very mature.

A little OT about the UI:
When storing code in graph db, programming becomes a graph problem and to display this graph a browser is the best solution (using SVG). I did a first start page with [reflex](https://github.com/ryantrinkle/reflex) that currently works only with Chrome: http://tkvogt.github.io/ 
When entering "a" you see all functions that contain "a" or have types that contain "a". Clicking on the arrows filters the list of functions. I also emplemented graph drawing algorithms and will build this into the UI. Its still big experiment if this works.
In the end it will be a plugin for the Atom-IDE.

**Comment by epost** [comment]
@JPMoresmau, @tkvogt: Cool stuff! This overlaps with my own view on what language tooling should be like, that is, something based on queries, allowing the tools to be very generic and powerful. I've been looking at it [through the lens of datalog](https://gist.github.com/epost/de87e67558a18de6716a) lately, as mgsloan indicated. I started [psc-query](https://github.com/epost/psc-query) as a first stab at converting PureScript sources to a datalog knowledge base. (The model used is naive, but it's just an example atm.)

To me, the specific database used doesn't seem like the most important thing, rather the possibility for the tools to present some of their functionality through queries. With something like that in place, one can always switch db's, as they're hidden between a nice data retrieval abstraction layer. That said, I think the graph/neo4j approach is potentially incredibly useful (though perhaps less so for editor support due to performance and licensing reasons?) and I'm following these discussions with great interest. If we could collaborate on this in some way, that would be awesome.

**Comment by tkvogt** [comment]
@epost I am definitely interested in collaboration.
I read a book about knowledge representation at university and this is definitely some very important aspect. An example: When I ask the IDE: 
- What can I apply to String?
doesn't give as good results as
- What can I apply to PersonId? Although this is also a String
So ontologies and automatic deduction could be crucial. I also remember that the more powerful the description languages are the harder it is to automatically deduce something. There is WOL, semantic web. But thats not what you have in mind I guess?

Datalog (Prolog) is obviously a real language and nothing can be deduced automatically. You have to write the queries yourself and then it's just the same as writing queries in SQL or Haskell (imho).
Prolog solves many problems with the same tricks (recursion) as Haskell, but it is limited in its expressivity. But one the other hand one can easily write down facts and rules. If I would come to the conclusion that if facts and rules were a help I would implement/use a rule based engine in Haskell which may not be as elegant as Prolog but probably faster. Representing a database as Prolog facts is most likely slow.
And the db definitely makes a difference. When you want to match a graph with 10 nodes, this is fast in a graph db, while it could be very slow in relational db (possibly 10 JOINs).

**Comment by JPMoresmau** [comment]
@tkvogt  I toyed around with AcidState for as-browser to avoid dependency on other tools and be able to develop the persistence in Haskell. I've done quite a lot of research on graph databases, not sure if I agree with you on Neo4J being "very mature". It takes a big graph traversal for a graph database to outperform a relational database... And I'm not too sure an IDE requires a deep graph. Yes you want to find dependencies between functions, say, but do you really care to find all the functions that call functions that call functions that call function X?
I haven't use graph-db, but if you're interested you can have a look at https://github.com/JPMoresmau/HGraphStorage, a little toy graph database that I made, trying to implement the low level storage ideas of Neo4J.

**Comment by tkvogt** [comment]
Please note that the following are just wild ideas:

I can imagine to have more than 4 nodes in a path the graph. If one has to solve the problem:

f :: (Int,Float,String) -> a    is nearly the same as 
g :: (Float,String,Int) -> b    or
h :: Float -> String -> Int -> c

@ndmitchell mentions this kind of matching in his [hoogle talk](http://community.haskell.org/~ndm/downloads/slides-hoogle_finding_functions_from_types-16_may_2011.pdf)
One could encode these similarities by automatically applying permutation functions or picking functions to every function.
This alone would double/triple the depth of a path and add n!  permutation-nodes to every function. Then  one could apply A*-search to find a path from a start to a goal node. When there is a type/ontology hierachy this also adds nodes to the graph. And one quickly has more than 10 nodes in a path.

About the performance I have no idea if this is feasible. The material from neo4j is maybe too cheering. But they received [20 million risk capital](http://neo4j.com/news/neo-technology-raises-20-million-in-series-c-funding/) and their [team on github](https://github.com/neo4j) is quite big. I must admit that made an impression to me.

> I haven't use graph-db, but if you're interested you can have a look at  https://github.com/JPMoresmau/HGraphStorage, a little toy graph database that I made, trying to implement the low level storage ideas of Neo4J.

This is funny. I read the chapter about internals of neo4j last week and thought: Why not directly accessing the binary data ... and you already did this. I will definitely take a look at it. It is no problem if it is not ACID. But it would be really cool if it were binary write compatible with neo4j: Writing data in a file and neo4j accepts it. Another option would be the [Bolt driver](https://github.com/boggle/neo4j-haskell-driver) that @boggle is doing.

**Comment by alanz** [comment]
I think specifying it as a constraint satisfaction problem is probably a good way to go.  Which comes back to an early suggestion to use something like datalog. Except there are no mature haskell implementations, to my knowledge

**Comment by epost** [comment]
TIL the Ensime Scala IDE folks (@fommil et al) are apparently considering the graph DB approach for their IDE to replace Lucene: https://github.com/ensime/ensime-server/issues/1133. They mention some very interesting points on that thread.

And now for some thinking out loud... :)

@tkvogt I think we may have slightly different use cases in mind, but that's ok, since I'm interested in learning about the limits of the applicability of the various modelling options (datalog, graph dbs or other). I think something like datalog would make more sense than, say OWL or SPARQL, since as far as I can tell we can assume a closed world, and get more powerful reasoning in return. Some things that I think separate datalog from (pre-99) SQL are its ability to do recursion and reasoning, and its ultra-concise syntax for stating the facts and rules of whatever concept space you're trying to model. That said, standard datalog has its limitations, and it's not yet clear to me which dialect would get us all the way.

To be clear, I'm not necessarily advocating the use of something external, like swi-prolog, and sending Prolog source text back and forth, because that would no doubt be too slow. What I *would* like, is to think about an abstract representation of the software facts implied by the source code and its libraries in terms of some well-defined semantics, which some appropriate datalog variety could provide, and to **implement some of the IDE service functionality in terms of a querying interface** instead of an ad hoc command interface like [ghc-mod](http://www.mew.org/~kazu/proj/ghc-mod/en/ghc-mod.html) and [psc-ide](https://github.com/kRITZCREEK/psc-ide/wiki/Protocol) have. Even if this starts out as a very restricted querying interface that can only resolve a few predetermined queries, such as `imports("My.Awesome.Module", SYMBOL)?` or `type("Control.Data.ap2", TYPE)?`, I think this would open up a whole world of possibilities for the future. (NB: I think the semantics here are much more important than whatever syntax is deemed suitable.) If it turns out that some graph querying language would be a better fit, that would be awesome too.

The same model could be reused by other tooling initiatives to provide support for other languages.  Since haskell-ide-engine will have to provide answers to questions like my two example queries anyway, I think it shouldn't be an extra burden to adhere to some predictable way of expressing them.

@alanz I'm aware of the (unfortunate) scarcity of mature Haskell datalog implementations. Initially, an external datalog system doesn't seem necessary, as we could pick a couple of fixed queries and hardcode them in Haskell. This could later be replaced by something external, if the effort is considered to be worth it. Whether that something has to be a Haskell library (yet to be written or improved), or whether something on the other end of a few FFI calls would do, I don't know.

**Comment by fommil** [comment]
we are not replacing Lucene, we are replacing H2 (i.e. relational databases). Lucene is an index, not a store, and can be used to complement any storage mechanism.

**Comment by fommil** [comment]
btw, talking of indexing and search and types and all that good stuff... we want to be able to do this https://github.com/ensime/ensime-server/issues/472 which is basically Hoogol for Scala. If you have any ideas on how this could be implemented with Lucene queries, we'd love to talk.

**Comment by alanz** [comment]
I started looking at DataLog after seeing a presentation on clojure/datomic

I wonder if it would be possible to use datomic from haskell? Although I seem to recall is is non-free

**Comment by fommil** [comment]
I'm going to unsubscribe from this because you'll have a lot of chatter going on, but feel free to use my handle if there is something you want me to chat about :smile:

**Comment by epost** [comment]
fommil: thanks for your comments! :)

@alanz: https://github.com/tonsky/datascript looks like a sort of in-memory datomic clone, which I suppose could be run on Node, as well as in the browser. I'm still wading through the morass of papers and github repos about various forms of datalog in search of useful implementations. I have noticed any are on the JVM. :/

**Comment by bitemyapp** [comment]
@alanz @epost You really don't want to use Datomic for anything. We used the paid version for a production laboratory information management system. It was really bad. Straight-forward stuff like, "kill runaway query", they refused to support even after we offered to pay them on contract to add the feature. This is just one example of many.

**Comment by epost** [comment]
@bitemyapp Oh, that's pretty bad. I don't think datomic's licensing is very pleasant anyway. It's got some cool ideas though.

**Comment by alanz** [comment]
Well, I am pretty sure there is a datalog implementation buried somewhere in https://github.com/ermine-language/ermine

**Comment by cocreature** [comment]
What do we do with this issue? There seems to be interest but we’re far from having something concrete and I’m also not sure if this belongs in `hie` or if it should just be yet another plugin (YAP :)). Don’t get me wrong, if we can get something concrete out of this I’m all for it, I just don’t like having open issues which become irrelevant because the project has moved on.

**Comment by mgsloan** [comment]
I think it should be yet-another-plugin.  While it'd be elegant to do all our info collection / query through something like this, I don't think it makes sense to block such essential features on a speculative idea.  In other words, to me it makes sense to experiment with it outside of core HIE.  It seems quite reasonable to use extensible plugin state to share such info between plugins.  If it becomes the primary way things are done, it can get cleaned up and moved into the core HIE package.

**Comment by alanz** [comment]
Agree. The core should focus on coordinating the mechanics of plugins only, features should come via the plugins.

**Comment by mgsloan** [comment]
Yup, closing!

The discussion here is very interesting, though, and the ideas are promising as well.  So, don't interpret this as "don't do that!" instead, it's just not an item for the main HIE project.

**Comment by tkvogt** [comment]
After several failed experiments I came to the conlcusion that I have to develop a graph database from scratch:
https://github.com/tkvogt/judy-graph-db
It is especially targeted at this problem, but still infant.
Look at some example code: https://github.com/tkvogt/judy-graph-db/blob/master/app/Main.hs
Feel free to open up issues.

**Comment by sboosali** [comment]
(should we mark this as wontfix instead, or something?)

**Comment by alanz** [comment]
@sboosali I think this is something we will do, at some point, but is not currently viable. So I propose we keep it open.

I have flagged it as an enhancement.
