### ISSUE TITLE
(emacs) "Selecting deleted buffer" after *hie* buffer killed

### ISSUE THREAD

**Issue by mgsloan** [haskell/haskell-ide-engine#121]
If you use `M-x kill-buffer` on the `*hie*` buffer, subsequent commands error out with "Selecting deleted buffer".  This is due to a use of `with-current-buffer (hie-buffer)`.  Maybe defining a utility like `with-hie-buffer` would be good, which also ensures that the buffer is initialized.

**Comment by ankhers** [comment]
I seem unable to reproduce this. I am doing the following

1. Open a Haskell file
2. Ensure `hie-mode` is running and the `*hie*` buffer is available
3. Switch to `*hie*` buffer
4. Call `M-x kill-buffer`
5. Within my Haskell file, try calling `hie-base-plugins`

I receive the following message

> Process Haskell IDE Engine not running

If this is still an issue, would you be able to provide me with the exact steps you use to get this message?

**Comment by cocreature** [comment]
@ankhers The buffers got refactored since @mgsloan opened that issue, but the general problem still exists.
Here’s an example:
1. Open a haskell file.
2. `M-x hie-mode`
3. `M-x hie-eg2-sayHello`
4. Kill the `*hie-log*` buffer
5. `M-x hie-eg2-sayHello`
In this case the error is in `hie-log` but from a quick look almost all cases where we use `with-current-buffer` suffer from that problem although it might be hard to reproduce it in some cases. We already have a `with-hie-refactor-buffer` macro so just adding macros for the other buffers and using them should be enough.
