### ISSUE TITLE
Drop 8.2.1 support?

### ISSUE THREAD

**Issue by bubba** [haskell/haskell-ide-engine#1249]
We're supporting quite a lot of builds right now, and 8.2.1 has been around for a while. If there is not a lot of interest in keeping it on then we should remove it make CI easier.
It'll also allow us to clean up all those CPP pragmas where we need to explicitly import Data.Semigroup

**Comment by alanz** [comment]
@Anrock that is version 8.0.2

Right now 8.2.1 is the odd one out, as it cannot accept an up to date hlint, for example, because of dependencies.

And it just started failing on appveyor for no good reason

**Comment by alanz** [comment]
@Anrock for some reason github believes you are in GMT+2, so thinks your posts are in 6 hours time.  Or maybe just matches my time zone. So for me the threading of our conversation is broken.

**Comment by nponeccop** [comment]
If the matter is Data.Semigroup and some GHC API #ifdefs we have anyway, I'm against the dropping.

CI is parallel anyway. If you want to drop a few CI jobs, it's better to drop some minor versions.

Oh, and while I have rights to commit, I don't. So treat this as a user voice. In both C++, Perl or Node.JS old versions are supported pretty well by IDEs because it's what production needs. As for GHC, I have some code using 7.4 because it supported Windows DLLs. And 8.2 is pretty modern, yesterday I saw a question on a Haskell gitter channel about 8.0.2.

**Comment by nponeccop** [comment]
Threading is definitely broken, hehe

**Comment by alanz** [comment]
How realistic is it that users are stuck on GHC 8.2.1, without being able to use GHC 8.2.2?

iirc, 8.2.1 was basically useless in any case.

**Comment by nponeccop** [comment]
> GHC 8.2.1, without being able to use GHC 8.2.2?

I don't mind dropping 8.2.1 if it's broken and there's unbroken 8.2.x we still support. After all, we have a similar situation with 8.6.3 broken on Windows

**Comment by lorenzo** [comment]
I don't think it is realistic to say people are stuck in 8.2.1 without being able to bump GHC to the next patch version.

**Comment by alanz** [comment]
Ok, so next release we will drop 8.2.1
