### ISSUE TITLE
Git integration

### ISSUE THREAD

**Issue by kjameslubin** [haskell/haskell-ide-engine#128]
Not sure if this is planned and obvious, (or possibly against the philosophy of `haskell-ide-engine`), but it is probably a good idea to be able to import a project from git with a single command. I have found it somewhat annoying to import projects into IDEs like Eclipse, IntelliJ, and we should do a better job at integrating. I like the way that `stack` handles its git support.

**Comment by cocreature** [comment]
At least in the current state `hie` doesn’t do project management but we expect an existing `cabal` or `stack` project. Until that changes I am not really sure what git integration would mean.

**Comment by kjameslubin** [comment]
Got it, thanks @cocreature. Just wanted to make sure you could "just clone"

**Comment by bergey** [comment]
It seems like everyone expects `hie` to work with either `stack` or `cabal`.  I hope at some point it will get functions to figure out the root directory of a project (eg, given a `.hs` filepath) and decide what build tool to use.  Otherwise every IDE has to write these functions, and uses different heuristics.  So maybe a little bit of project management?

**Comment by mgsloan** [comment]
@bergey This is already done by ghc-mod.  It finds the root directory and decides to use stack or cabal.
