### ISSUE TITLE
Create default parameter for word at point

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#129]
In emacs, if I put the cursor on a symbol and invoke (via the menu) any command that needs a one word symbol (such as ghc-mod find command), the word that point is on should be provided.

But perhaps this should always be sent through, in the same way we always send through the file name, start or region and end of region, if they are set.

It could be a standard variable "word-under-cursor" or some such.

Thoughts?

**Comment by mgsloan** [comment]
This makes sense to me.  Ideally, we'd have a precise spec for the expected behavior of a given editor's word-under-cursor.  In particular:

* Include name qualification (handling bizarre cases like `A.b.C.d`, which is really `A.b . C.d`)

* Also provide operator-at-point

The alternative to having a precise spec for expected behavior is to base it off syntax highlighting tokens.  This could make it easier to implement for some editors, but it also makes it less likely to behave consistently between them.  I also prefer something that's based on local text, as it's potentially quite handy to do queries on identifiers within comments.

# Declaration-At-Point

It'd also be handy to have a "declaration-at-point" function, which makes a guess of the text span corresponding to the current declaration.  This would be useful for adding structured-haskell-mode / hindent support, as that's how they work (allowing them to work even when the file doesn't compile).  It'd also be useful for things like giving 

I realize this could be controversial, but I suggest that "declaration-at-point" be specified to be a simple guess that works for normal haskell styles.  It would find the start of the declaration by looking for a place where column 0 has a character in it, ignoring lines that start with `--`, `{-`, `#`, or `|]`.  Finding the end of the declaration works similarly, but doesn't include the line that starts at column 0.

It might be worthwhile to try to do something special about `{- -}` and `[qqs|  |]`, but I don't think the added complexity is worth it.

**Comment by alanz** [comment]
I think having it work on a symbol in a commented out stretch of code could be useful. So keeping it simple may be beneficial. At the end of the day, the user places the cursor, and asks a question. They must have some idea that it is something worth looking up.

**Comment by cocreature** [comment]
What I would like is a prompt that asks for that parameter and uses the one under point if none is specified. This way we only need one command which also means we only need one keybinding (you run out of those at some point :)) and the overhead is literally pressing the return key a single time if you don’t want to change it.

**Comment by cocreature** [comment]
So that also means that I don’t think we should always send it.

**Comment by tobiasgwaaler** [comment]
I like that idea a lot @cocreature

**Comment by mgsloan** [comment]
> What I would like is a prompt that asks for that parameter and uses the one under point if none is specified.

It seems to me like the main utility of identifier-at-point is that it works even when the current file doesn't compile (and potentially works with things that don't get compiled, like strings and comments).  Since you can just type into the buffer and query from that, I think I prefer not prompting by default.

Of course, this is a matter of discretion for the editor integrator.  While HIE can have some documentation with suggestions for how editors behave, this sort of thing should be left up to the editor plugin author / the user's configuration.

**Comment by cocreature** [comment]
@mgsloan Do you think the overhead of pressing `Return` is too big for the case where you don’t want to change it? For the case where I want to change it typing something into a file just to be able to run a command on it feels really weird.

**Comment by cocreature** [comment]
So if we go for not prompting by default I want a function that does prompt by default.

**Comment by mgsloan** [comment]
Yeah, having a prompt could indeed work well for some commands. Only one way to find out - try it and see how it feels.

This stuff should definitely be customizable, at least in the emacs implementation.

**Comment by cocreature** [comment]
We could go for not prompting by default unless a prefix argument (`C-u`) is specified. That seems like a good compromise.

**Comment by alanz** [comment]
One of the drivers for this function would be to place the cursor on a variable and press a hot-key to get its type, without having to enter additional information. So a direct option is important.

Perhaps we could extend the parameter tylpes in the spec to include "symbol at point", either in the context definitions or in the additional params. And declaration at point etc.

**Comment by cocreature** [comment]
To be honest I think the type example is not that good since type info can better be done by providing a point than a name, but I’m already sold to make the default not prompting and use the prefix argument to activate the prompt.

I would prefer symbol at point to be a normal parameter in additional params, but I don’t have very strong feelings there. When it comes to declaration at point, I am not completely sure how easy it is to parse the declaration for the IDE so I could imagine that we do the parsing once on the HIE side so the editor just provides the point and a flag and then HIE figures out which declaration this point belongs to. But this is getting off the original discussion here, so let’s discuss that separately.

**Comment by gracjan** [comment]
Emacs has thing-at-point:

http://www.gnu.org/software/emacs/manual/html_node/elisp/Buffer-Contents.html#index-thing_002dat_002dpoint

Note that thing-at-point needs to be thought how to span Haskell things.
There is haskell-lexeme.el file in haskell-mode that has the needed
functionality.

**Comment by gracjan** [comment]
Also note that `forward-sexp` (C-M-f) works correctly, `backward-sexp` is missing though.

**Comment by mgsloan** [comment]
> To be honest I think the type example is not that good since type info can better be done by providing a point than a name

When the current module doesn't compile, we should still be able to give a form of type info for imported identifiers.  Ideally, we'd be able to have info about imports regardless of whether a module compiles or not.  We have such information in ide-backend, though IIRC it might be info from the last successful compile of the module.

Usecases like this are what make me thing that it shouldn't prompt by default.  The only time when the prompt is useful is when the current module doesn't compile (so might as well type the identifier you're interested in into the buffer).

**Comment by alanz** [comment]
Superseded by move to LSP
