### ISSUE TITLE
Using HIE completely as a library?

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#150]
On #ghc, Phyx- said

```
<Phyx-> bgamari: https://mistuke.files.wordpress.com/2010/07/screenshot1.png (old version)
 and http://i.imgur.com/1eNUnLc.png (new code) lol.
* Phyx- does too many things at once
<bgamari> wow
<bgamari> Phyx-, looks quite good
<bgamari> Phyx-, you should do a better job advertising this
<Phyx-> bgamari: well, I never finished it. Still have the code though. Been attempting to
 clean it up to release it
<Phyx-> has things like https://mistuke.files.wordpress.com/2010/08/image.png as
 well, where hovering over anything shows you the definition
<Phyx-> it hooks directly into GHC's ASTs, so things like enabling language pragmas
 will change syntax highlighting etc. which is the biggest difference between it and the
 rest of the stuff out there which just use regexp
<bgamari> indeed
<bgamari> Phyx-, have you considered building on haskell-ide-engine?
<Phyx-> bgamari: Haven't looked at that one, at the time I did look at scion. But the
 serialization to and from strings made it fairly unusable for the responsiveness I wanted.
<Phyx-> If there's enough abstraction it may be possible with haskell-ide, so I'll
 have a look
```

<img src="https://mistuke.files.wordpress.com/2010/07/screenshot1.png">

<img src="http://i.imgur.com/1eNUnLc.png">

<img src="https://mistuke.files.wordpress.com/2010/08/image.png">

and

```
<Phyx-> alanz: My approach has been to compile my IDE backend which just exposes
 simplified GHC types to a shared library (which includes the GHC api bits) and load it
 in the same address space as the IDE and just marshall the data acros. The reason
 I've done this is that in my own testing, JSON, XML and even MSGPACK were just
 not responsive enough. Lots of time was wasted on the printing and parsing. The way
 scion, ghc-mod and it seems this project is structured, it hea
 [01:47:59]
<Phyx-> alanz: as in, If I were to use haskell-ide-engine, can I bypass the protocol and
 write just straight FFI exports to the functions? without having to fight the setup?
 [01:49:00]
<thomie> Phyx-: your sentence was cut off at "The way scion, ghc-mod and it seems
 this project is structured, it hea" [02:05:01]
<Phyx-> whoops [02:05:32]
<Phyx->  The way scion, ghc-mod and it seems this project is structured, it [02:05:36]
<Phyx->                   heavily relies on having a "protocol" in place. [02:05:36]
```

To me the main thing to do to allow this is to push all the serialisation out to the transport layer, and then provide an FFI transport.

**Comment by cocreature** [comment]
Let’s first take a look at our current architecture and then see how an ffi approach can fit in here and what changes it requires:

Currently we have a single `TChan` which receives `ChannelRequest`s. The transport is responsible for delivering the requests to the channel and our dispatcher reads the requests. The `ChannelRequest` contains the channel used to transfer back the output.

#### Problems
Now we can obviously just expose those channels via an ffi, but there are two problems with this approach:

1. A channel takes a single type, that means that the output of a plugin needs to be “serialized” to that type. Currently this is a `ChannelResponse` which contains an `aeson` `Object` inside containing the actual data. If the serialization speed of aeson is a problem, I strongly suspect that serializing to an `Object` is also not an option. Obviously `ChannelResponse` can contain something else. The best case for performance would probably be a giant sum type which in Phyx-’s case needs a constructor for the things ghc’s parser returns. "Serializing" becomes then as cheep as attaching a tag, so it should no longer be a problem. However this approach is not very extensible. Since sum types are closed, every time a plugin has a new return value we need to extend this.

2. The second issue is more subtle: `TChan`s are a nice abstraction when used from haskell, but I don’t think they are a good fit if you want to use them via the ffi. Whatever language your using probably has it’s own channel abstraction and I am pretty sure that it’s nicer to use those than do some weird ffi things just to be able to work with `TChan`s.

So overall I don’t think exposing the channels is enough to get a nice ffi.

### A possible solution
I would prefer if an ffi approach could completely bypass any channels and dispatchers we may use. We already have the `CommandFunc a` type which doesn’t do any serialization, it comes in an async and a sync version so if you only need sync support you don’t need to deal with channels,callbacks or something else like that and if you need async commands then you can use a callback to convert to whatever concurrency abstraction your language provides. Great! However it’s not quite that simple. The `CommandFunc`s don’t simply work in `IO` but in `IdeM` so you can’t just call them directly via the ffi. However it shouldn’t be too hard to provide a wrapper which returns in IO.
So let me illustrate how I would imagine an ffi approach looks like
```
initialize haskell runtime
mvarContainingSomeState <- initiHIE
wrapper mvarContainingSomeState syncCommandFunction
wrapper mvarContainingSomeState asyncCommandFunction callback
```

I’d love to hear if I’ve forgotten anything or if there are better ways.

**Comment by Mistuke** [comment]
{{{
initialize haskell runtime
mvarContainingSomeState <- initiHIE
wrapper mvarContainingSomeState syncCommandFunction
wrapper mvarContainingSomeState asyncCommandFunction callback
}}}

Something like this would actually work perfectly fine for me!

**Comment by alanz** [comment]
Superseded by move to LSP
