### ISSUE TITLE
status update?

### ISSUE THREAD

**Issue by rvion** [haskell/haskell-ide-engine#198]
Hello, I was just wondering what is currently going on.

Is haskell-ide-engine developpement paused until ghc8 ? 
Is this project still strong and alive ?
Are GHCi's new ide-related features / faast speed / good defer-error-at-runtime integration / etc.  going to make ghci a core component of haskell-ide-engine vs ghc-mod ?

**Comment by cocreature** [comment]
I can obviously only speak for myself so let me explain why I was a bit quiet/haven’t done much. There are basically two reasons:

1. I was busy with exams, they are now over but I’m starting to write my bachelor thesis so I don’t know if I’ll have much more time in the next months.
2. I went through a phase of frustration with IDE tooling so I lost motivation to work on it.

That said let me answer your specific questions:
- I think @alanz was pretty busy with GHC 8 so that was probably the reason why he didn’t do much recently.
- Depends on how you define strong and alive. It’s definitely not dead, but if the people contributing to it no longer do so (the reasons for that don’t really matter) it’s at least temporarily slowed down.
- @alanz tried to integrate GHCi at some point but it was quiet difficult. GHC 8 has the remote GHCi stuff in it which should make this a lot easier. However it won’t replace our use of ghc-mod anytime soon. We mainly use ghc-mod for project management and GHCi obviously doesn’t do this. @DanielG has been working on extracting some parts of ghc-mod into a separate package/rewriting them, specifically the project management but I don’t know what the current state of that is. I’ve also started working on a [manager proxy](https://github.com/cocreature/haskell-ide-engine/blob/hie-manager/hie-manager/src/Haskell/Ide/Engine/Manager/Main.hs) but put that on hold because I wasn’t sure how it would interact with the new ghc-mod stuff.

So all in all what we really need are just more contributors willing to work on things so if Alan and I are busy, development continues. Personally I plan to start working on hie again soon, but I won’t promise anything.

**Comment by alanz** [comment]
As @cocreature has said, my side slowed down as I had to sort out the API Annotations update for GHC 8, and due to unrelated reasons my available time for doing this has been limited in the first part of the year.

The new ghci is definitely something to be worked in, but I have been waiting for GHC 8 to come out, which has taken much longer than expected. When that happens, all the other libraries and components can be finally updated for it and then the new work can start.

**Comment by rvion** [comment]
Thanks you very much for your answers !
