### ISSUE TITLE
Integrate brittany

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#215]
See https://github.com/lspitzner/brittany/issues/5

**Comment by lspitzner** [comment]
what kind of interface of brittany would make this possible? I have not really considered the usage of brittany as a library before, but could certainly be done. You'd probably want some `Annotations->Annotations` transformation instead of a the raw `Text->Text`, or something else?

**Comment by alanz** [comment]
Perhaps based on something like https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#document-formatting-request

Or what hindent does.

Operationally, it would take text and return text.

**Comment by alanz** [comment]
Base it on current HIE, modelled on the HaRe plugin and responding to https://github.com/alanz/haskell-lsp/blob/master/src/Language/Haskell/LSP/TH/DataTypesJSON.hs#L3680

by doing it something like https://github.com/haskell/haskell-ide-engine/blob/master/src/Haskell/Ide/Engine/Transport/LspStdio.hs#L287

**Comment by lspitzner** [comment]
For a start, brittany dev branch now exposes

~~~~.hs
-- | Exposes the transformation in an pseudo-pure fashion. The signature
-- contains `IO` due to the GHC API not exposing a pure parsing function, but
-- there should be no observable effects.
--
-- Note that this function ignores/resets all config values regarding
-- debugging, i.e. it will never use `trace`/write to stderr.
parsePrintModule :: Config -> Text -> IO (Either [BrittanyError] Text)
~~~~

(where there is `staticDefaultConfig :: Config`.)

usage in simplest form can be seen in [this testcase](https://github.com/lspitzner/brittany/blob/27af1c2349a474384596445790a9c88976459c11/src-libinterfacetests/Main.hs#L15).
