### ISSUE TITLE
Session Management

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#226]
Starting a new GHC session is time consuming.

I want to move toward a model more like Intero, where you choose a target and then work in that context, and it is then the live session.

All the info etc commands should be able to continue in the same session then, just reloading parts as they change.

Will have to consider how this affects the plugin architecture, if at all.

**Comment by alanz** [comment]
Apropos this, with the LSP focus it will start a fresh hie instance per project.  This means that from a ghc-mod perspective we will only have one cradle, so should consider running the whole reactor in a single `GhcModT` session, as previously suggested by @DanielG

**Comment by wz1000** [comment]
I don't think this is a good idea as we wouldn't be able to have seperate
threads for the reactor and the dispatcher.

On 19-Jun-2017 2:28 AM, "Alan Zimmerman" <notifications@github.com> wrote:

Apropos this, with the LSP focus it will start a fresh hie instance per
project. This means that from a ghc-mod perspective we will only have one
cradle, so should consider running the whole reactor in a single GhcModT
session, as previously suggested by @DanielG <https://github.com/danielg>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/haskell/haskell-ide-engine/issues/226#issuecomment-309302521>,
or mute the thread

**Comment by alanz** [comment]
After making my comment, I looked at the code. The dispatcher [already runs this way](https://github.com/haskell/haskell-ide-engine/blob/master/hie-plugin-api/Haskell/Ide/Engine/Monad.hs#L18), which is good. So setting the project root before starting the dispatcher gives us a single ghc-mod "instance" dedicated to the project root.

I have no idea what this means for projects such as HIE with multiple sub-projects, but this is the same problem that other backends face too. One thing at a time.
