### ISSUE TITLE
Multiple errors, can't get it working

### ISSUE THREAD

**Issue by paparga** [haskell/haskell-ide-engine#337]
Hi, I don't know what I'am doing wrong, I installed accordingly to readme.

**My machine configuration:**
```
stack exec ghc -- --version
The Glorious Glasgow Haskell Compilation System, version 8.0.2

stack exec ghc-mod -- --version
ghc-mod version 5.6.0.0 compiled by GHC 8.0.1

hie --version                  
Version 0.1.0.0, Git revision e3a663c3af9347395b2752fda695a88dc7f0d614 (1050 commits) x86_64

Haskell Language Server: 0.0.3

Visual Studio Code:  1.17.2

OS: Ubuntu 16.04
```
**First errors:**
```
[Error - 4:21:13 PM] haskell-lsp:Got setTraceNotification ignoring
[Error - 4:21:13 PM] haskell-lsp:didChangeConfiguration error. NotificationMessage {_jsonrpc = "2.0", _method = WorkspaceDidChangeConfiguration, _params = DidChangeConfigurationParams {_settings = Object (fromList [("languageServerHaskell",Object (fromList [("maxNumberOfProblems",Number 100.0)]))])}} "key \"hlintOn\" not present"
```
**Multiple errors when a file is loaded, one example**
```
hie: /home/pablo/.stack/snapshots/x86_64-linux/lts-9.0/8.0.2/lib/x86_64-linux-ghc-8.0.2/amazonka-core-1.4.5-6ewvKv6LVRcGluzUWvfjBm/libHSamazonka-core-1.4.5-6ewvKv6LVRcGluzUWvfjBm.a: unknown symbol `httpzmconduitzm2zi2zi3zi2zmKbWgdP1kl6c5Klwqtnczzrh_NetworkziHTTPziConduit_srcToPopper_info'
hie: Could not on-demand load symbol 'amazzonkazmcorezm1zi4zi5zm6ewvKv6LVRcGluzzUWvfjBm_NetworkziAWSziDataziBody_HashedBytes_con_info'
```

**On textDocument/hover:**
```
[Error - 4:26:00 PM] Request textDocument/hover failed.
  Message: IdeError {ideCode = PluginError, ideMessage = "getSymbolAtPoint: \"module not loaded\"", ideInfo = Null}
  Code: -32603
```

Anyone knows what is happening?

**Comment by sword865** [comment]
I got similar error on mac:

````
[Error - 12:28:31] haskell-lsp:Got setTraceNotification ignoring
[Error - 12:28:31] haskell-lsp:didChangeConfiguration error. NotificationMessage {_jsonrpc = "2.0", _method = WorkspaceDidChangeConfiguration, _params = DidChangeConfigurationParams {_settings = Object (fromList [("languageServerHaskell",Object (fromList [("maxNumberOfProblems",Number 100.0)]))])}} "key \"hlintOn\" not present"
````

**Comment by saurabhnanda** [comment]
Some config file is missing the hlintOn key, from what the error message it
saying.

On 25-Oct-2017 10:04 AM, "Howie Tien" <notifications@github.com> wrote:

I got similar error on mac:

[Error - 12:28:31] haskell-lsp:Got setTraceNotification ignoring
[Error - 12:28:31] haskell-lsp:didChangeConfiguration error.
NotificationMessage {_jsonrpc = "2.0", _method =
WorkspaceDidChangeConfiguration, _params =
DidChangeConfigurationParams {_settings = Object (fromList
[("languageServerHaskell",Object (fromList
[("maxNumberOfProblems",Number 100.0)]))])}} "key \"hlintOn\" not
present"

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/haskell/haskell-ide-engine/issues/337#issuecomment-339211666>,
or mute the thread

**Comment by alanz** [comment]
Sorry, my bad. Please try https://github.com/alanz/haskell-ide-engine/tree/wip to sort out the config message missing field problem
