### ISSUE TITLE
Add Emacs Support to README?

### ISSUE THREAD

**Issue by IvanMalison** [haskell/haskell-ide-engine#338]
Is there a reason that emacs support is not mentioned in the README.

It seems that @vibhavp is actively developing https://github.com/emacs-lsp/lsp-haskell

**Comment by Arulselvanmadhavan** [comment]
+1 for emacs support.

**Comment by Tehnix** [comment]
If it works I'd say let's add it to the README. I do wish the install instructions were a bit better though, so even emacs newbies (like myself) could follow a bit more easily. I also think it is worth to add explicit instructions on how to make it work with something like Spacemacs, since that very often gets recommended in the Haskell community, I feel like.

@IvanMalison Is that something you would be up for making a PR for?

**Comment by IvanMalison** [comment]
@Tehnix Maybe, but I actually haven't yet managed to get this working very well. From https://github.com/emacs-lsp/lsp-mode/graphs/contributors
It seems that @vibhavp and @alanz have done the most work on lsp-mode. There is also https://github.com/emacs-lsp/lsp-haskell, and it seems that this was recently updated with a significant change in https://github.com/emacs-lsp/lsp-haskell/commit/b4c84e48321e6c1710ed566a90d4508ddabde6f8

When I had tried it earlier it didn't seem to work, but perhaps that was a due to the mismatch in api interface between lsp-mode and lsp-haskell.

It's a little unclear to me what state emacs support is in. @vibhavp or @alanz could you clarify?

**Comment by alanz** [comment]
I am getting close to using this in my day-to-day work, and I set it up according to the README on  https://github.com/emacs-lsp/lsp-haskell.

But this is all on the back burner at the moment, as I focus on some GHC stuff, as there is a deadline approaching.

**Comment by IvanMalison** [comment]
@alanz I guess my question is whether the emacs support is "ready enough" to be listed on the README.
