### ISSUE TITLE
Implicit forall

### ISSUE THREAD

**Issue by nponeccop** [haskell/haskell-ide-engine#367]
Now neovim displays `print` in completion dialog as

```
print     [Function] [LC] forall a. Show a => a -> IO ()^@Prelude
```
Why not cut the `forall` for rank-1 types? It takes space in the list of completions so the signature gets truncated:
```
writeIORef         [Function] [LC] forall a. IORef a -> a ->..()^@Data.IORef
```
Also I wonder if it's feasible to suppress module names as well if someone wants to see longer signatures at the cost of less info.

**Comment by ktonga** [comment]
Yeah, that's really annoying. Can I help somehow to solve this?

**Comment by lorenzo** [comment]
@ktonga You would have to modify this function https://github.com/haskell/haskell-ide-engine/blob/master/src/Haskell/Ide/Engine/Plugin/HieExtras.hs#L103 so that the forall is stripped and add a few tests in this file https://github.com/haskell/haskell-ide-engine/blob/master/test/functional/CompletionSpec.hs

**Comment by ktonga** [comment]
Thanks for the hint @lorenzo I'll take a look.
