### ISSUE TITLE
Atom integration currently not working on Windows

### ISSUE THREAD

**Issue by soylens** [haskell/haskell-ide-engine#427]
`ide-haskell-hie` states that it has to communicate with HIE using TCP/sockets due to blocking STDIO on windows.
(See https://github.com/Tehnix/ide-haskell-hie/blob/master/lib/ide-haskell-hie.js function `startServerProcess`)
I suppose that https://github.com/haskell/haskell-ide-engine/issues/196 has to do with this.
We better update the README to clarify this. But see VS Code integration works under windows, I actually doubt this is really the case.

**Comment by nponeccop** [comment]
> VS Code integration works under windows

Windows perfectly supports non-blocking stdio either via threads :) or via overlapped io. Some runtimes ported from Unix world support neither. For example GHC currently has relatively poor IO implementation for Windows, e.g. no IOCP/overlapped IO. But fortunately it does support threads on Windows, so `hie` uses that approach.

**Comment by soylens** [comment]
I deleted thePlatform checks in the integration and checked again.
Here are some results.
HIE starts.
Formatting
Atom Linter shows that there are suggestions available but does not display them.
I dont know if this has to do with the `blocking stdio`

**Comment by Tehnix** [comment]
Ah, I never really got around to the Windows part in the Atom client since I didn't have Windows to test on.

I gathered from looking at the other LSP clients that Windows needed special handline (e.g. https://github.com/atom/ide-php/blob/master/lib/main.js#L26), but that might be a wrong assumption 🤔 

I could simply remove the OS check, and try to see if we get some results, if someone is up for testing it? (You can manually quickly do it in the Atom plugin folder yourself). It would just be making `startServerProcess` only return `return this.spawnServer()`.

**Comment by Tehnix** [comment]
@soylens If you could try the Atom integration again, that would be awesome! As for the logging, you can set the HIE logging path in the settings pane for `ide-haskell-hie`, which should allow you to get some further debugging info.

**Comment by soylens** [comment]
Yup, as of now, the only problem seems to be Linter.
BTW, it still doesn't process the files outside the current opened folder, which I think is a bug/feature of linter or Atom itself.

**Comment by nponeccop** [comment]
Can we close this issue and open the one that describes current state of Atom support on Windows better?

**Comment by soylens** [comment]
Sure. It's better when the team takes care of it @nponeccop
