### ISSUE TITLE
Very slow / hangs

### ISSUE THREAD

**Issue by razvan-flavius-panda** [haskell/haskell-ide-engine#519]
For example open this repository using HIE for Atom or VSCode and then open `Build.hs`, in both editors the CPU will get maxed out for minutes (I don't know if it ever stops). During this time Atom interface hangs and nothing is being shown on hover in any of them.

**Comment by Infinisil** [comment]
I'm getting this too now, hasn't happened with the HIE version I used previously (I think that was c68ba8d5cfb9cb89d04efd2bbda575d055a5e10b, now using master (d769a30608cd5393cdffcece38549cc6269942ed)). I could do a bisection if that's wanted.

It's unbearably slow, hangs for around 3 minutes at 100% CPU. Looking at the system calls (via htop) reveals no calls happening. No subprocesses running either. The logs silent during that time, and my emacs hangs upon typing during that time.

It happens every time HIE gets restarted, there's no caching happening.

**Comment by Infinisil** [comment]
Here are the logs of my ~4 minute hang at the start: https://gist.github.com/d480967ced87f011a6782890fa83dfd9

Ping @Bubba

**Comment by Infinisil** [comment]
Note that this slowdown only happens exactly once during a HIE run. And it happens whenever it first encounters a module using template haskell. This means I can write a simple
```haskell
module Main where
main = putStrLn "hi"
```
then start HIE, everything fine, no slowdown. Then I can add
```haskell
{#- LANGUAGE TemplateHaskell -#}
module Main where
main = putStrLn "hi"
```

and the slowdown happens (4 minutes), after that everything works fine again, I can even remove template haskell again and readd it, no slowdown ever again in that HIE session.

I can then restart HIE on that file, and the slowdown happens on startup again, because template haskell is present then.

**Comment by Infinisil** [comment]
With latest master, the problem isn't there (06de34eb53667a6b90ead0907dd002156b1638ab)

**Comment by Infinisil** [comment]
Aha! This is due to hie-nix doing static linking by default. I've now switched to my new https://github.com/infinisil/all-hies and will merge https://github.com/Infinisil/all-hies/pull/3 soon which fixes it.

**Comment by jneira** [comment]
Afaiu this one could be closed, feel free to reopen if it is not the case
