### ISSUE TITLE
On Windows make stops with "cp: cannot stat '/home/zmtemp/.local/bin/hie': No such file or directory

### ISSUE THREAD

**Issue by MuratOzsoyler** [haskell/haskell-ide-engine#537]
Windows 10
stack Version 1.7.0.3,  x86_64 hpack-0.28.2
haskell-ide-engine repo has been cloned recently

After some compilation and haddock folder access errors finally the first phase (stack-8.0.2.yaml) compiled but make couldn't continue to the second phase with this error (sorry for bad characters):

```
[0mhaskell-ide-engine-0.1.0.0: copy/register[0m
[0mCompleted 22 action(s).[0m
[0mLog files have been written to: C:\Users\zmtemp\Desktop\haskell\packages\haskell-ide-engine\.stack-work\logs\[0m
[0mCopying from C:\Users\zmtemp\Desktop\haskell\packages\haskell-ide-engine\.stack-work\install\71c8e9f1\bin\hie.exe to C:\Users\zmtemp\AppData\Roaming\local\bin\hie.exe[0m
[0m[0m
[0mCopied executables to C:\Users\zmtemp\AppData\Roaming\local\bin:[0m
[0m- hie.exe[0m
cp: cannot stat '/home/zmtemp/.local/bin/hie': No such file or directory
make: *** [Makefile:4: build] Error 1
```
After I created /home/zmtemp/.local/bin/hie directory in msys2 terminal, the error message changed to this:
```
cp: -r not specified; omitting directory '/home/zmtemp/.local/bin/hie'
make: *** [Makefile:4: build] Error 1
```

**Comment by Anrock** [comment]
I'm using `make build-copy-compiler-tool`, so stack handles copying binaries to proper locations. Not sure why it's not default target.

**Comment by Anrock** [comment]
@alanz yes. There is no `/home` dir on Windows, obviously. Why even copy hie binary to ~/.local/bin/hie-x.y.z?

**Comment by alanz** [comment]
I guess the Makefile needs a platform-specific destination.

PR's welcome, I have no idea where it should go, or how to detect that it is on windows.

**Comment by Anrock** [comment]
@alanz so can you answer:
1. Why `make build-copy-compiler-tool` is not a default target? Is there any downsides?
As i said earlier if copy-compiler-tool was the default target - it would solve this issue because stack handles per-compiler tools building and copying just fine. I also use `stack exec hie -- --lsp` as a command for LSP client in neovim to start HIE.

2. Why even copy hie binary to `~/.local/bin/hie-x.y.z`? Is it just arbitrary destination for per-user binaries or some part of HIE\VSCode plugin\whatever depends on it?
If it's arbitrarily chosen i think a solution might be in introducing a variable in Makefile for destination. It would be prepopulated for osx\linux (where .local/bin is a sane place to put a per-user binary) and unpopulated for Windows, because i don't think there is some standard or common destination for this kind of binaries.

**Comment by alanz** [comment]
The reason for the `hie-x.y.z` names is that otherwise you cannot have more than one version of hie installed at a time.  And the GHC used to compile a given hie version needs to match the GHC version used in the project you are using hie against.

And the Makefile approach is a hacky workaround for this, which is now only works on Linux.

I think it is possible to ask stack to give the location that it will install an exe, perhaps we can modify the makefile to do that.
