### ISSUE TITLE
Makefile broken on macos

### ISSUE THREAD

**Issue by newhoggy** [haskell/haskell-ide-engine#574]
This change from `2018-05-16` broke the `Makefile` my macos environment:

```
$ git blame Makefile | head -n 3
5370b013 (Christian Kjaer Laustsen 2018-01-24 11:02:08 +0100  1) BASEDIR=$(CURDIR)
9691675e (Vladislav Shtepin        2018-05-16 01:02:42 +0300  2) STACKLOCALBINDIR != stack path --local-bin
5370b013 (Christian Kjaer Laustsen 2018-01-24 11:02:08 +0100  3)
```

This is the error I get:

```
cp: /hie: No such file or directory
```

After patching this line, the build works again:

```
diff --git a/Makefile b/Makefile
index 85f4159..b73266c 100644
--- a/Makefile
+++ b/Makefile
@@ -1,5 +1,5 @@
 BASEDIR=$(CURDIR)
-STACKLOCALBINDIR != stack path --local-bin
+STACKLOCALBINDIR:=$(shell stack path --local-bin)

 build: hie-8.2.1 hie-8.2.2 hie-8.4.2
 # build: hie-8.0.2 hie-8.2.1 hie-8.2.2 hie-8.4.2
```

**Comment by Tehnix** [comment]
Just tried the `make build` (I usually do `make build-copy-compiler-tool`), and it seems https://github.com/haskell/haskell-ide-engine/commit/9691675e6537c8d8e56fc9abeb5baa711ee422f8#diff-b67911656ef5d18c4ae36cb6741b7965 broke support for macOS at least (don't have linux at hand right now).

The problem is that `STACKLOCALBINDIR != stack path --local-bin` does not return anything on macOS, but the patched command fixes this `STACKLOCALBINDIR:=$(shell stack path --local-bin)`.

Does `STACKLOCALBINDIR:=$(shell stack path --local-bin)` also work on Linux? Cause then I would say we should switch to this.

**Comment by Anrock** [comment]
I can confirm that `STACKLOCALBINDIR:=$(shell stack path --local-bin)` works at Windows atleast. 
Sorry for breaking things for MacOs.

**Comment by Tehnix** [comment]
No worries at all! I think macOS is on an older version of make or something.

@Anrock would you be up for making a PR with this change, if you have time? :)

**Comment by Anrock** [comment]
@Tehnix 
> No worries at all! I think macOS is on an older version of make or something.
AFAIK it uses BSD version of make which doesn't support `$(shell ...)`, that's why i've used `!=` operator. Looks like it didn't help and\or made things worse.

> would you be up for making a PR with this change, if you have time? :)
Will do in a couple of minutes.
