### ISSUE TITLE
Commands should define what they return

### ISSUE THREAD

**Issue by JPMoresmau** [haskell/haskell-ide-engine#61]
Following a discussion on IRC between @alanz and @gracjan, we think commands should be explicit in the type of response they return, and we should offer some concrete types out of the box, so that plugin authors can reuse the types for responses, which in turn means that editors using the API can have a good chance at supporting a wide range of plugin commands.

The idea is to define a type class that contains a function to serialize to something generic like JSON.

I have started some code and it looks promising (the fact that command definition carry the type they return). I obviously need a bit more time.

**Comment by alanz** [comment]
Great.

It is always easier to have a discussion based on concrete code.

**Comment by gracjan** [comment]
Let me write my incoherent thoughts in here and we will sort it out together later on (and move it to documentation).

**I try to look from Editor point of view**. Editor plugin writer will need to be able to semantically handle and act upon answer received from HIE. I think we have quite okay story with messages going from Editor to HIE: that is where the Context comes in, with projects, files, current cursor location and current marked region (if any). It is expected that plugins and plugin commands understand this common context to act on the part of source code a user has indicated on the screen.

Likewise there should be a preferably small set of responses coming from plugins, because Editor needs to know what to do with those. Note that Editor integration development will be asynchronous with respect to HIE development (in general, currently we can have it synced).

There are three sets of things that interact:
- set of request types
- set of response types
- set of editors
- set of plugins

If sets of requests and responses types is limited then editors and plugins are free to be developed at their own paces. The more tied are requests and responses the more coupling is in the whole system. Would be best to strive to have as little of it as reasonably possible.

**Comment by alanz** [comment]
@gracjan can you perhaps enumerate some small number of types that we are likely to need, I presume something like

* Warnings/errors to be displayed to the user
* Some kind of thing to be put on an overlay over the source
* A diff
* ???

**Comment by gracjan** [comment]
Lets me see:

- `{"version_info": {"git_commit_hash": "xxx", "commit_count": ...}}`
- `{"diff" : ... }
- `{"source_message": {"type":warning","span": [12,12], "text": "Expected type Int, got String", "fixups": { diffs }}`
- `{"symbol_info": { ... about :info from ghci, but structured }}`

I agree there will be a mix of generic and specialized requests and responses.

Note that the hardest part to implement will be to have some kind of dialog with user:

1. User selects a region, initiates command.
2. Command needs to ask about something.
3. User gives an answer, command gets it, continues.
4. Maybe go to step 2 again, maybe finish here.

Source code inspector will be pretty involved too, because it needs to return structured information that can help with navigating deeper in the structure.

**Comment by epost** [comment]
Perhaps this could be useful? http://json-schema.org/

**Comment by alanz** [comment]
This has been superseded by our concentration on LSP.
