### ISSUE TITLE
HIE fails in Atom with Cabal project

### ISSUE THREAD

**Issue by bratfizyk** [haskell/haskell-ide-engine#830]
I can't get anything but syntax highlight while working with a cabal project. Spec:
* OS: Linux Mint 19
* Editor: Atom

To reproduce: Just run "cabal init" in your folder and add a source file with simple main. I can't see e.g. type hover hints. Instead, I get the error:

`Got error while processing diagnostics: readCreateProcess: /home/beko/Apps/haskell-ide-engine/.stack-work/install/x86_64-linux/lts-12.8/8.4.3/libexec/x86_64-linux-ghc-8.4.3/cabal-helper-0.8.1.0/cabal-helper-wrapper "--with-ghc=ghc" "--with-ghc-pkg=ghc-pkg" "--with-cabal=cabal" "/home/beko/Dev/Haskell/tmp/greeter" "/home/beko/Dev/Haskell/tmp/greeter/dist" "package-db-stack" "flags" "compiler-version" "ghc-merged-pkg-options" "config-flags" "non-default-config-flags" "ghc-src-options" "ghc-pkg-options" "ghc-lang-options" "ghc-options" "source-dirs" "entrypoints" "needs-build-output" (exit 1): failed`

When I run the command specified by the error, I get a bunch of exceptions all of the same kind:

`Linking /home/beko/.cache/cabal-helper/cabal-helper0.8.1.0-Cabal2.2.0.0 ...
/usr/bin/x86_64-linux-gnu-ld.gold: error: /home/beko/.cache/cabal-helper/cabal-helper0.8.1.0-Cabal2.2.0.0.build/CabalHelper/Shared/Common.o: requires unsupported dynamic reloc 11; recompile with -fPIC`

I guess I need to pass additional parameters to build process. The question is: how ? :)

**Comment by DanielG** [comment]
You can set `CABAL_HELPER_DEBUG=1` in the environment when running the failed command, that should give you the ghc command line that's being used here. You can then try running it with `-fPIC` as suggested but I doubt that'll fix it.

This smells like a assembler/linker version mismatch to me, kind of like https://ghc.haskell.org/trac/ghc/ticket/12147 but not quite since it's gold complaining and not GHCi. There is a very simmilar issue on the stack tracker  https://github.com/commercialhaskell/stack/issues/3877 though that's with GHC 8.2.2 it has exactly the same error message.

I guess since gold has it's issues sometimes trying with GNU ld might be worth a shot, passing `-pgml-fuse-ld=ld` to the ghc command from above should do that (assuming your distro doesn't symlink ld -> gold).

**Comment by Anrock** [comment]
Looks like env\upstream issue. Closing as non-actionable.
