### ISSUE TITLE
Separate dispatcher stuff away from LspStdio

### ISSUE THREAD

**Issue by bubba** [haskell/haskell-ide-engine#835]
Currently `R` inside LspStdio holds a lot of mutable vars that are used by the dispatcher, which has caused some pains in #831. This should be tidied up so that these vars are handled inside `Dispatcher.hs` exclusively, so that multiple instances of `R` can be safely run.

**Comment by lorenzo** [comment]
@bubba @alanz What do you think of using something like `unagi-chan` as part of this refactor?

One thing that I missed having in #831 is the notion of the `in` and `out` ends of a channel. So instead of having to guess if a channel is used for publishing or reading, we can convey this meaning using the type system.

I think it this would make storing channels in the `R` environment a lot safer, since most of them are just for reading instead of writing, with the exception of the cancel channel.

**Comment by bubba** [comment]
I was thinking we could probably go a level further and just completely remove the notion of channels with just some functions
```haskell
cancelRequest :: LspId -> DispatcherEnv -> IO ()
makeRequest :: a -> DispatcherEnv -> IO ()
```

Where `DispatcherEnv` becomes an opaque type in `Dispatcher.hs` returned in one of the functions that kicks off the dispatcher. Although I do like the idea of in/out channels. Could we roll our own?

**Comment by alanz** [comment]
I have been thinking that the channel interface to the dispatcher could be replaced by calls to an explicit scheduler.  At the end of the day we are coordinating between two processes, the one must put things into a work queue, something must decide what is the next thing to work on (scheduler), and the work must happen.

Because there are two processes, some kind of safe communication primitive is needed.

**Comment by lorenzo** [comment]
@alanz Isn't the channel a safe primitive for communicating?
