### ISSUE TITLE
diagnostics different on save vs on edit

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#839]
https://github.com/alanz/vscode-hie-server/issues/81#issuecomment-422217276

**Comment by lorenzo** [comment]
@alanz should we also trigger diagnostics in save?

For me this would be handy, as sometimes neovim gets stuck in an old diagnostics state (seems to be missing messages) and saving to refresh the state would be an easy win.

**Comment by lorenzo** [comment]
I’ll did a bit further then and see if I can make this situation better.

**Comment by cah6** [comment]
I'd like to +1 this and chime in since this is probably the biggest issue that's stopping me from going all in on HIE. 

It seems like nearly every time I type something into the editor on VSC, it doesn't capture the last few keystrokes, which will almost always result in a compile error that does NOT go away when hitting the save key. From comments here, it seems like this is not specific to VSC. For example:
![screen shot 2018-11-18 at 1 44 35 pm](https://user-images.githubusercontent.com/2652649/48983129-21b62000-f0b9-11e8-955d-0dfdd69cbd01.png)
When typing in "initial", it seemed like it didn't capture "ial", and for some reason doesn't auto-correct over time or with a save. It will stay like this until I'm forced to change something in the file, which for me is typically adding and removing a space on an empty line. @alanz is there some setting I'm missing that will force a ghcmod refresh on save?

**Comment by telser** [comment]
I can confirm that a whole team of users see what @cah6 is mentioning. Disabling ghcmod checks until a save would be fantastic.

**Comment by bubba** [comment]
Some pointers on where to go with this from IRC:
- [ ] Set up test cases
- [ ] Look at disabling debouncing on saves
- [ ] Investigate the fact that save requests are not versioned

http://hackage.haskell.org/package/haskell-lsp-types-0.8.0.1/docs/Language-Haskell-LSP-Types.html#t:DidSaveTextDocumentParams
http://hackage.haskell.org/package/haskell-lsp-types-0.8.0.1/docs/Language-Haskell-LSP-Types.html#t:DidChangeTextDocumentParams

**Comment by alanz** [comment]
A possible remedy is at https://github.com/alanz/haskell-ide-engine/tree/issue-839

I will look at it more tomorrow, unless @bubba does now.
