### ISSUE TITLE
force a project type

### ISSUE THREAD

**Issue by teto** [haskell/haskell-ide-engine#963]
Using hie on nix, because there is .cabal file and/or dist/ subfolder, hie/ghc-mod will use the cabal mode which fails with import errors (for packages installed via nix, I suppose ghc-mod would expect these packages to have been installed via cabal instead). If I remove the .cabal file, hie/ghc-mod falls back "to plain GHC project" which works. 
My problem is that I use haskdogs to generate haskell tags and this needs the cabal file to work. Thus I would like to force hie to use a "plain GHC project" but I don't know how.

**Comment by benkolera** [comment]
I don't get errors when I have cabal files around and only have things
installed via nix (and am running hie in a nix-shell). As long as those
cabal files actually include all of your deps, of course, but this is a
useful thing to do anyway since you can use the cabal as the source of
truth and cabal2nix your nix setup (easier to release stuff to hackage
later if you always do this). If cabal can find the packages it needs in
the global ghc env, it will be happy and not need to install anything. Run
`ghc-pkg list` in the nix shell to see what is available in your project.

Be wary though of new build if you are using it. It will make a
.ghc.environment directory that will be picked up by cabal and you must
cabal new-clean to get rid of that cached env. I actually delete that file
every time I enter the shell just to be sure. It is currently not
disable-able in cabal. https://github.com/haskell/cabal/issues/4542 :(

The only hassle here is to make sure that you manually do a cabal update &&
cabal configure inside the nix shell when you change your nix environment
(and blow away .ghc.envs on entering shells). I have shortcuts in my editor
to restart hie and cabal configure to smooth off these edges. It could be
better, but it's way better than the alternatives! :)

**Comment by alanz** [comment]
This is something I have considered doing for a while now, especially on hie itself where you are working with multiple stack.yaml files and need to be able to specify a particular one. Or sometimes testing stack, sometimes new-build, etc,

**Comment by alanz** [comment]
Related
- #941 
- #942

**Comment by teto** [comment]
@benkolera I might have had a discrepancy between my cabal file and what was installed via nix as I was experimenting. 
Anyway it seems like I always have some kind of missing import as in 
`import qualified Data.Map as Map` => `daemon.hs|34 col 1 error| Could not find module ‘Data.Map’ Use -v to see a list of the files searched for.`

I added
`	exposed-modules:   Data.ByteString`
to my cabal file and it seems to make the error disappear.

**Comment by IvanMalison** [comment]
@alanz I'd like to add this, but what is the preferred approach here? Should it be a cl flag? What should be provided with the flag? Compiler version to use? Whether or not to use slack?

**Comment by IvanMalison** [comment]
@alanz ping.

In #942 you write:

>Closing in favour of #963 which is a more general solution

but this issue doesn't really seem to describe any particular solution. It seems like having

`--with-compiler` and `--stack-yaml` flags seems like about as good as a solution as one could hope for.

It might also be nice to have something like a --default-ghc to explicitly override stack usage without needing to specify the compiler.

**Comment by jneira** [comment]
Now hie has the option to force using one build tool using explicit `hie.yaml` files: https://github.com/haskell/haskell-ide-engine#configuration
An there is an issue about forcing it with a cli arg: #1432
